#!/bin/bash
# Make a gnirehtet release.
#
# Put your keystore properties into ~/.gradle/gradle.properties
# (check app/build.gradle)

set -e # fail on error

GRADLE=${GRADLE:-./gradlew} # set value ./gradlew if not set
DIST=dist

version=$(git describe --tags --always)
"$GRADLE" releaseJava
mkdir -p "$DIST"
cd "$DIST"
cp ../app/build/outputs/apk/gnirehtet-release.apk gnirehtet.apk
cp ../relay/build/libs/gnirehtet.jar .
cp ../relay/gnirehtet ../relay/gnirehtet.cmd .
target=gnirehtet-"$version".zip
rm -f "$target"
zip "$target" gnirehtet.apk gnirehtet.jar gnirehtet gnirehtet.cmd
sha256sum "$target" > SHA256SUM.txt
