#!/bin/bash
# Make a gnirehtet release.
#
# Put your keystore properties into ~/.gradle/gradle.properties
# (check app/build.gradle)

set -e # fail on error

GRADLE=./gradlew  # remplace by gradle if you want to
DIST=dist

version=$(git describe --tags --always)
"$GRADLE" release
mkdir -p "$DIST"
cd "$DIST"
cp ../app/build/outputs/apk/gnirehtet-release.apk gnirehtet.apk
cp ../relay/build/libs/relay.jar .
cp ../gnirehtet .
target=gnirehtet-"$version".zip
rm -f "$target"
zip "$target" gnirehtet.apk relay.jar gnirehtet
sha256sum "$target" > SHA256SUM.txt
